import React from 'react';
import { BookOpen, HelpCircle, CheckCircle2, ShieldCheck, Scale } from 'lucide-react';

export default function DocumentationView() {
  return (
    <div className="documentation-container">
      <div className="ink-card">
        <div className="ink-card-header">
          <div className="card-title-block">
            <div className="card-icon-wrap">
              <BookOpen size={18} />
            </div>
            <div>
              <h2 className="card-heading">Platform Documentation & Methodology</h2>
              <p className="card-subtext">How PROOFRAG validates responses and calculates factual metrics</p>
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '28px', fontSize: '0.88rem', lineHeight: 1.55 }}>
          {/* Overview */}
          <section>
            <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '8px', color: 'var(--text-primary)' }}>
              1. What is PROOFRAG?
            </h3>
            <p style={{ color: 'var(--text-secondary)' }}>
              PROOFRAG is an AI response validation and evidence grounding platform. It cross-examines
              AI-generated responses against verified reference knowledge bases (such as TruthfulQA and SQuAD)
              and user-supplied source documents to evaluate topical relevance, verify factual correctness,
              and detect unsupported assertions or hallucinations.
            </p>
          </section>

          {/* Evidence Retrieval */}
          <section>
            <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '8px', color: 'var(--text-primary)' }}>
              2. Semantic Evidence Retrieval & Relevance Filtering
            </h3>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '8px' }}>
              The retrieval engine uses 384-dimensional dense embeddings generated by <code>all-MiniLM-L6-v2</code>.
              To maximize retrieval recall, it executes a dual-query candidate expansion:
            </p>
            <ul style={{ paddingLeft: '20px', color: 'var(--text-secondary)', display: 'flex', flexDirection: 'column', gap: '4px' }}>
              <li><strong>Question Query:</strong> Retrieves topical reference passages relevant to the inquiry.</li>
              <li><strong>Joint Claim Query:</strong> Expands search to include assertions made within the AI answer.</li>
            </ul>
            <p style={{ color: 'var(--text-secondary)', marginTop: '8px' }}>
              Candidates are evaluated against engineering match tiers:
              <br />• <strong>Strong Match (≥ 70%):</strong> Authoritative supporting context.
              <br />• <strong>Moderate Match (50%–69%):</strong> Partial or related topic context.
              <br />• <strong>Weak Match (&lt; 50%):</strong> Limited or distant evidence; classified as <em>Limited Evidence</em> to avoid false grounding.
            </p>
          </section>

          {/* Evaluation Dimensions */}
          <section>
            <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '8px', color: 'var(--text-primary)' }}>
              3. Evaluation Dimensions & Agent Roles
            </h3>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '14px', marginTop: '8px' }}>
              <div style={{ padding: '14px', backgroundColor: 'var(--bg-surface-subtle)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)' }}>
                <h4 style={{ fontWeight: 700, marginBottom: '4px' }}>Relevance Judge (1–5)</h4>
                <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>
                  Assesses whether the response directly addresses the question and stays focused on the prompt.
                  Detects off-topic or evasive answers.
                </p>
              </div>

              <div style={{ padding: '14px', backgroundColor: 'var(--bg-surface-subtle)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)' }}>
                <h4 style={{ fontWeight: 700, marginBottom: '4px' }}>Accuracy Judge (1–5)</h4>
                <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>
                  Evaluates factual correctness using prioritized hierarchy:
                  (1) Verified Answer, (2) Supporting Document, (3) Retrieved Knowledge Base Evidence.
                </p>
              </div>

              <div style={{ padding: '14px', backgroundColor: 'var(--bg-surface-subtle)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)' }}>
                <h4 style={{ fontWeight: 700, marginBottom: '4px' }}>Hallucination Check</h4>
                <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>
                  Breaks the response into atomic claims and assigns one of 4 statuses:
                  <strong>SUPPORTED</strong>, <strong>UNSUPPORTED</strong>, <strong>CONTRADICTED</strong>, or <strong>INSUFFICIENT_EVIDENCE</strong>.
                </p>
              </div>
            </div>
          </section>

          {/* Scoring Methodology */}
          <section>
            <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '8px', color: 'var(--text-primary)' }}>
              4. Overall Score & Verdict Calculation
            </h3>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '8px' }}>
              The overall evaluation score is calculated via transparent weighted aggregation:
            </p>
            <div style={{ padding: '12px 16px', backgroundColor: 'var(--bg-surface-subtle)', borderRadius: 'var(--radius-md)', fontFamily: 'var(--font-mono)', fontSize: '0.82rem', border: '1px solid var(--border-subtle)' }}>
              overall_score = round( (accuracy/5.0 * 0.40 + relevance/5.0 * 0.30 + hallucination_safety * 0.30) * 100 )
            </div>
            <p style={{ color: 'var(--text-secondary)', marginTop: '8px' }}>
              Where <code>hallucination_safety</code> equals 1.0 (NONE), 0.5 (PARTIAL), or 0.0 (HIGH).
              <br /><br />
              <strong>Verdict Rules:</strong>
              <br />• <strong>PASS:</strong> Accuracy ≥ 4, Relevance ≥ 4, Risk = LOW, Score ≥ 75, no contradicted claims.
              <br />• <strong>FAIL:</strong> Accuracy ≤ 2, Relevance ≤ 2, Contradicted claims &gt; 0, or Risk = HIGH.
              <br />• <strong>REVIEW:</strong> Mixed ratings, partial accuracy, or insufficient reference evidence.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
